Class {
	#name : #CNNFamixUnknownSourceLanguage,
	#superclass : #CNNFamixSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'CNN-Famix-Entities-Entities'
}

{ #category : #meta }
CNNFamixUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #CNNFamixSourceLanguage>
	<package: #'CNN-Famix-Entities'>
	<generated>
	^ self
]
