Class {
	#name : #CNNFamixSourceTextAnchor,
	#superclass : #CNNFamixSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'CNN-Famix-Entities-Entities'
}

{ #category : #meta }
CNNFamixSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #CNNFamixSourceAnchor>
	<package: #'CNN-Famix-Entities'>
	<generated>
	^ self
]
