Class {
	#name : #CNNFamixIndexedFileAnchor,
	#superclass : #CNNFamixSourceAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'CNN-Famix-Entities-Entities'
}

{ #category : #meta }
CNNFamixIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #CNNFamixSourceAnchor>
	<package: #'CNN-Famix-Entities'>
	<generated>
	^ self
]
